import {StyleSheet} from 'react-native';
import Colors from '../../utils/Colors';
import Fonts from '../../utils/Fonts';

export const style = StyleSheet.create({
  body: {
    flex: 1,
    backgroundColor: Colors.PRIMARY_BACKGROUND_COLOR,
  },
  signInHeaderContainer: {
    alignItems: 'center',
    position: 'relative',
    marginTop: 12,
  },
  signInHeaderText: {
    fontFamily: Fonts.MONTSERRAT_BOLD,
    fontWeight: '500',
    color: Colors.SECONDARY_TEXT_COLOR,
    fontSize: 24,
  },
  mainContainer: {
    marginTop: 41,
    marginHorizontal: 14,
    borderColor: 'black',
  },
  mainContainerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  headerText: {
    fontFamily: Fonts.MONTSERRAT_REGULAR,
    fontWeight: '700',
    fontSize: 16,
    color: Colors.Text_COLOR,
  },
  selectedHeaderText: {
    fontFamily: Fonts.MONTSERRAT_REGULAR,
    fontWeight: '700',
    fontSize: 16,
    color: Colors.BLUE_PRIMARY,
  },
  line: {
    borderWidth: 1,
    height: 24,
    borderColor: Colors.LINE_COLOR,
  },
  inputSectionContainer: {
    marginTop: 37,
    // borderWidth: 1,
  },
  labelText: {
    fontWeight: '700',
    marginBottom: 11,
    fontSize: 15,
    fontFamily: Fonts.MONTSERRAT_REGULAR,
    color: Colors.SECONDARY_TEXT_COLOR,
  },
  passLabel: {
    fontWeight: '700',
    marginTop: 20,
    marginBottom: 11,
    fontSize: 15,
    fontFamily: Fonts.MONTSERRAT_REGULAR,
    color: Colors.SECONDARY_TEXT_COLOR,
  },
  numberInputSection: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    paddingLeft: 10,
    backgroundColor: '#F1F1F1',
  },
  numberInput: {
    marginLeft: '1%',
    width: '100%',
    fontFamily: Fonts.MONTSERRAT_REGULAR,
    fontWeight: '700',
    fontSize: 14,
  },
  passwordInput: {
    backgroundColor: '#F1F1F1',
    fontSize: 14,
    fontWeight: '500',
    borderRadius: 10,
    paddingLeft: 10,
  },
  partician: {
    borderWidth: 1,
    height: 27,
    borderColor: '#ACB1C4',
  },
  rfContainer: {
    flexDirection: 'row',
    marginTop: 14,
    justifyContent: 'space-between',
  },
  subContainer: {
    flexDirection: 'row',
  },
  rememberBox: {
    marginRight: 6,
  },
  rememberText: {
    fontWeight: '600',
    fontSize: 14,
    color: Colors.SECONDARY_TEXT_COLOR,
  },
  forgetText: {
    fontWeight: '600',
    fontSize: 14,
    color: Colors.BLUE_PRIMARY,
  },
  continueText: {
    color: Colors.PRIMARY_TEXT_COLOR,
    fontFamily: Fonts.MONTSERRAT_REGULAR,
    fontWeight: '700',
  },
  continueContainer: {
    backgroundColor: Colors.BUTTON_CONTAINER_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    paddingTop: 17,
    paddingBottom: 17,
    paddingLeft: 136,
    paddingRight: 136,
    borderRadius: 10,
  },
  continueContainerActive: {
    backgroundColor: Colors.BLUE_PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    paddingTop: 17,
    paddingBottom: 17,
    paddingLeft: 136,
    paddingRight: 136,
    borderRadius: 10,
  },
  orContainer: {
    marginTop: 28,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  leftLine: {
    marginTop: 9,
    height: 0,
    width: 150,
    borderColor: '#EDF1F3',
    borderWidth: 1,
    marginRight: 6,
  },
  rightLine: {
    marginTop: 9,
    height: 0,
    width: 150,
    borderColor: '#EDF1F3',
    borderWidth: 1,
    marginLeft: 6,
  },
  orText: {
    fontFamily: Fonts.MONTSERRAT_REGULAR,
    color: '#676E87',
    fontWeight: '700',
  },
  continueWithContainer: {
    marginTop: 28,
  },
  continueWithFB: {
    flexDirection: 'row',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 17,
    paddingBottom: 17,
    borderRadius: 10,
  },
  continueWithGoogle: {
    flexDirection: 'row',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    paddingTop: 17,
    paddingBottom: 17,
    borderRadius: 10,
  },
  btnText: {
    fontWeight: '700',
    color: Colors.SECONDARY_TEXT_COLOR,
    fontFamily: Fonts.MONTSERRAT_MEDIUM,
  },
  bottomContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 137,
  },
  question: {
    fontFamily: Fonts.MONTSERRAT_MEDIUM,
    fontSize: 16,
    fontWeight: '500',
    color: Colors.SECONDARY_TEXT_COLOR,
  },
  signUpText: {
    fontWeight: '700',
    fontFamily: Fonts.MONTSERRAT_MEDIUM,
    fontSize: 16,
    color: Colors.BLUE_PRIMARY,
  },
});
