export default {
  PRIMARY_TEXT_COLOR: 'white',
  BOARDING_BAR_COLOR: '#0FD500',
  SECONDARY_TEXT_COLOR: '#000231',
  Text_COLOR: '#676E87',
  LINE_COLOR: '#E2E2E2',
  PRIMARY_BACKGROUND_COLOR: '#FFFFFF',
  BLUE_PRIMARY: '#0077F9',
  PLACEHOLDER_COLOR: '#ACB1C4',
  BUTTON_CONTAINER_COLOR: '#B6B6B6',
  OTP_BOX_BACKGROUND: '#F0F0F0',
  ERROR_TEXT_COLOR: 'red',
  BLACK: '#000000',
};
